"""Canonical schema for an incoming disaster reporting.

A "reporting" is one thing a person (or an agency, or a sensor) told us —
typically a call-centre call, but equally an email, a form submission, a social
post or a partner-agency update. Everything downstream (triage, dedupe, map,
audit, handover) operates on this shape.

Two rules the schema enforces on purpose:

1. `source.permalink` and `raw` are always preserved, so an operator can get
   back to the original words. Nothing we infer replaces what was actually said.
2. Anything the machine derived lives under `triage`, never mixed into
   `content`. The UI can therefore always show "what came in" separately from
   "what we think about it".
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class Channel(str, Enum):
    phone_call = "phone_call"
    email = "email"
    web_form = "web_form"
    social_media = "social_media"
    news = "news"
    partner_agency = "partner_agency"
    sensor = "sensor"
    other = "other"


class MediaKind(str, Enum):
    image = "image"
    video = "video"
    audio = "audio"
    document = "document"


class CaptionSource(str, Enum):
    author = "author"      # the person who filed it wrote this
    operator = "operator"  # a staff member wrote this
    model = "model"        # generated — must be labelled as such in the UI


class GeoMethod(str, Enum):
    device_gps = "device_gps"
    user_pin = "user_pin"
    operator = "operator"
    post_geotag = "post_geotag"
    profile = "profile"
    gazetteer = "gazetteer"       # we matched a place name in free text
    text_inference = "text_inference"
    unknown = "unknown"

    @property
    def is_precise(self) -> bool:
        return self in (GeoMethod.device_gps, GeoMethod.user_pin,
                        GeoMethod.post_geotag, GeoMethod.operator)


class Priority(str, Enum):
    """The three buckets the problem statement asks for."""
    action_required = "action_required"
    verification_required = "verification_required"
    situational_awareness = "situational_awareness"


PRIORITY_RANK = {
    Priority.situational_awareness: 0,
    Priority.verification_required: 1,
    Priority.action_required: 2,
}

PRIORITY_LABEL = {
    Priority.action_required: "Action required",
    Priority.verification_required: "Verification required",
    Priority.situational_awareness: "Situational awareness",
}


class Status(str, Enum):
    """Workflow state. Distinct from priority — a reporting can be
    `action_required` and still `new` (nobody has picked it up yet), which is
    exactly the thing a shift handover has to surface."""
    new = "new"
    acknowledged = "acknowledged"
    in_review = "in_review"
    verified = "verified"
    false_reporting = "false_reporting"
    forwarded = "forwarded"
    actioned = "actioned"
    closed = "closed"
    duplicate = "duplicate"


OPEN_STATUSES = {Status.new, Status.acknowledged, Status.in_review,
                 Status.verified, Status.forwarded}


class EngineMode(str, Enum):
    rules = "rules"
    llm = "llm"
    hybrid = "hybrid"


# ---------------------------------------------------------------------------
# Input envelope
# ---------------------------------------------------------------------------


class MediaItem(BaseModel):
    kind: MediaKind = MediaKind.image
    url: Optional[str] = None
    thumbnail_url: Optional[str] = None
    caption: Optional[str] = None
    caption_source: Optional[CaptionSource] = None
    model_caption: Optional[str] = Field(
        default=None,
        description="Caption generated by a vision model. Always rendered with "
                    "an 'AI-generated' label — never shown as the author's words.",
    )
    mime_type: Optional[str] = None
    captured_at: Optional[datetime] = None


class SourceRef(BaseModel):
    """Where this came from, and how far we can trust the channel itself."""
    channel: Channel = Channel.other
    system: Optional[str] = Field(
        default=None, description="Originating system, e.g. 'WCC Contact Centre', 'x'.")
    external_id: Optional[str] = Field(
        default=None, description="Stable id in the origin system. Used to reject duplicates on re-ingest.")
    permalink: Optional[str] = Field(
        default=None, description="Link back to the original. The problem statement "
                                  "requires we never lose this.")
    author_handle: Optional[str] = None
    author_display_name: Optional[str] = None
    received_at: datetime = Field(default_factory=utcnow)
    ingested_by: Optional[str] = Field(
        default=None, description="Which pipeline/team pushed this in.")
    credibility_hint: Optional[float] = Field(
        default=None, ge=0.0, le=1.0,
        description="Optional upstream credibility score. Advisory only.")


class Content(BaseModel):
    text: Optional[str] = None
    transcript: Optional[str] = Field(
        default=None, description="Call-centre call transcript, verbatim.")
    subject: Optional[str] = None
    summary: Optional[str] = Field(
        default=None, description="Machine summary. Labelled as such in the UI.")
    language: str = "en"
    media: list[MediaItem] = Field(default_factory=list)

    def searchable(self) -> str:
        parts = [self.subject, self.text, self.transcript]
        parts += [m.caption for m in self.media if m.caption]
        parts += [m.model_caption for m in self.media if m.model_caption]
        return "\n".join(p for p in parts if p)


class LocationHint(BaseModel):
    text: Optional[str] = Field(
        default=None, description="Location as the person described it.")
    lat: Optional[float] = None
    lon: Optional[float] = None
    accuracy_m: Optional[float] = None
    method: GeoMethod = GeoMethod.unknown
    suburb: Optional[str] = None
    confidence: Optional[float] = Field(default=None, ge=0.0, le=1.0)

    @property
    def has_coords(self) -> bool:
        return self.lat is not None and self.lon is not None

    @property
    def is_precise(self) -> bool:
        return self.has_coords and self.method.is_precise


class Reporter(BaseModel):
    """Contact details. Kept out of the repo's seed data — the demo corpus uses
    invented names and dummy addresses only."""
    name: Optional[str] = None
    phone: Optional[str] = None
    email: Optional[str] = None
    organisation: Optional[str] = None
    is_official: bool = False


class Signal(BaseModel):
    """One rule that fired, kept so the operator can see *why* a priority was
    assigned. This is what makes the triage assistive rather than a black box."""
    rule_id: str
    label: str
    score: float
    rationale: Optional[str] = None


class TriageResult(BaseModel):
    priority: Priority = Priority.situational_awareness
    score: float = 0.0
    category: str = "general"
    category_label: str = "General"
    confidence: float = 0.5
    rationale: str = ""
    signals: list[Signal] = Field(default_factory=list)
    engine: EngineMode = EngineMode.rules
    ruleset_version: Optional[int] = None
    model: Optional[str] = None
    # Set when the ruleset and the LLM disagreed. Surfaced in the UI rather
    # than silently resolved — the operator decides.
    disagreement: Optional[str] = None
    llm_priority: Optional[Priority] = None
    llm_rationale: Optional[str] = None
    computed_at: datetime = Field(default_factory=utcnow)


class Reporting(BaseModel):
    """The canonical record."""
    id: str = Field(default_factory=lambda: new_id("rpt"))
    source: SourceRef = Field(default_factory=SourceRef)
    content: Content = Field(default_factory=Content)
    occurred_at: Optional[datetime] = None
    location: Optional[LocationHint] = None
    reporter: Optional[Reporter] = None
    tags: list[str] = Field(default_factory=list)
    raw: dict[str, Any] = Field(
        default_factory=dict,
        description="The original payload, verbatim. Never modified.")

    # --- assigned by us -----------------------------------------------------
    triage: Optional[TriageResult] = None
    priority: Priority = Priority.situational_awareness
    priority_overridden: bool = False
    override_reason: Optional[str] = None
    status: Status = Status.new
    cluster_id: Optional[str] = None
    duplicate_of: Optional[str] = None

    # --- shift-handover critical fields ------------------------------------
    acknowledged_by: Optional[str] = Field(
        default=None, description="First human to open this. If null at end of "
                                  "shift, nobody has looked at it — the exact "
                                  "miss the handover briefing must catch.")
    acknowledged_at: Optional[datetime] = None
    assigned_to: Optional[str] = None
    ingested_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)
    ingest_shift_id: Optional[str] = None

    def effective_text(self) -> str:
        return self.content.searchable()


class IngestResult(BaseModel):
    accepted: int = 0
    duplicates_rejected: int = 0
    ids: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Audit + shifts
# ---------------------------------------------------------------------------


class AuditAction(str, Enum):
    ingested = "ingested"
    triaged = "triaged"
    retriaged = "retriaged"
    viewed = "viewed"
    acknowledged = "acknowledged"
    priority_overridden = "priority_overridden"
    status_changed = "status_changed"
    marked_false = "marked_false"
    cluster_flagged_false = "cluster_flagged_false"
    note_added = "note_added"
    assigned = "assigned"
    forwarded = "forwarded"
    forward_failed = "forward_failed"
    linked_duplicate = "linked_duplicate"
    shift_started = "shift_started"
    shift_ended = "shift_ended"
    handover_generated = "handover_generated"
    config_changed = "config_changed"
    ruleset_generated = "ruleset_generated"


# Actions that represent a human decision, as opposed to machine bookkeeping.
# The handover briefing leads with these.
DECISION_ACTIONS = {
    AuditAction.priority_overridden, AuditAction.status_changed,
    AuditAction.marked_false, AuditAction.cluster_flagged_false,
    AuditAction.forwarded, AuditAction.note_added, AuditAction.assigned,
    AuditAction.linked_duplicate,
}


class AuditEvent(BaseModel):
    id: str = Field(default_factory=lambda: new_id("aud"))
    at: datetime = Field(default_factory=utcnow)
    reporting_id: Optional[str] = None
    shift_id: Optional[str] = None
    actor: str = "system"
    is_human: bool = True
    action: AuditAction
    field: Optional[str] = None
    from_value: Optional[str] = None
    to_value: Optional[str] = None
    note: Optional[str] = None
    detail: dict[str, Any] = Field(default_factory=dict)


class Shift(BaseModel):
    id: str = Field(default_factory=lambda: new_id("shf"))
    operator: str
    role: str = "Duty controller"
    started_at: datetime = Field(default_factory=utcnow)
    ended_at: Optional[datetime] = None
    handover_note: Optional[str] = None

    @property
    def is_open(self) -> bool:
        return self.ended_at is None


class Forward(BaseModel):
    id: str = Field(default_factory=lambda: new_id("fwd"))
    reporting_id: str
    destination_id: str
    destination_name: str
    transport: str            # "email" | "api"
    target: str               # address or URL
    note: Optional[str] = None
    sent_at: datetime = Field(default_factory=utcnow)
    sent_by: str = "system"
    shift_id: Optional[str] = None
    dry_run: bool = True
    ok: bool = True
    response: Optional[str] = None
    payload: dict[str, Any] = Field(default_factory=dict)
    acknowledged_at: Optional[datetime] = Field(
        default=None,
        description="Set when the receiving agency confirms. Until then the "
                    "handover briefing lists this as awaiting a reply.")
